---

commands:
  - gradle build

# Exclude these hosts and IP addresses from network monitoring
host_whitelist:
  - 10.0.2.2 # VirtualBox's address
  - downloads.gradle.org
  - repo.maven.apache.org
  - repo1.maven.org
  - services.gradle.org

# Files or directories which should be included or excluded from evidence collection
evidence_files:
  exclude:
    - /backup
    - /dev
    - /evidence
    - /home/vagrant/.gradle
    - /home/vagrant/repo
    - /lost+found
    - /media
    - /mnt
    - /proc
    - /run
    - /sys
    - /tmp
    - /vagrant
    - /var/lock
    - /var/log
    - /var/run
    - /var/tmp
  include:
    - /bin
    - /boot
    - /etc
    - /home
    - /lib
    - /opt
    - /root
    - /sbin
    - /selinux
    - /srv
    - /usr
    - /var
